### ISSUE TITLE
JATS Reader and code blocks

### ISSUE THREAD

**Issue by nokome** [stencila/pandoc#4]
The JATS reader does not appear to handle code blocks. For example the following Markdown

    ```r
    # Some R code
    ```

Gets converted to JATS OK, `pandoc -f gfm -t jats temp.md > temp.jats`

    <code language="r script"># Some R code
    </code>

But not back again `pandoc -f jats -t gfm temp.jats`:

    \# Some R code

**Comment by hamishmack** [comment]
I have fixed this with https://github.com/stencila/pandoc/commit/9467b688b99f1edd036025980d047240b7492023 in the `jats-code-lang` branch.  I'll send a pull request to upstream after https://github.com/jgm/pandoc/pull/4177 is merged.  I have uploaded linux and macOS binaries with the fix to [jats-9](https://github.com/stencila/pandoc/releases/tag/jats-9).

**Comment by nokome** [comment]
Thanks!
